openapi: 3.0.3
info:
  title: Invoice Example Process API
  version: '1.0'
  summary: |2+


    Created at 06/06/2023, 17:32

    ****

    .. in a Spring Boot Web Application for Camunda 7.

    > A standalone example to use [Camundala](https://github.com/pme123/camundala) for BPMN development.

    I bundled it here! Just run `InvoiceServletProcessApplication`.

    This based on this Project: https://github.com/pme123/spring-boot-datakurre-plugins

    ## Original

    > This is the invoice demo application which is shipped with the full distributions.

    See the original [README](https://github.com/camunda/camunda-bpm-platform/tree/master/examples/invoice).



paths:
  /process/InvoiceReceiptP:
    head:
      tags:
      - InvoiceReceiptP
      summary: 'Process: InvoiceReceiptP'
      description: |+
        This starts the Invoice Receipt Process.


        <div class="diagramCanvas">
          <div class="diagram" id="InvoiceReceiptP-63530">
            <img onLoad="openFromUrl('InvoiceReceiptP.bpmn', new BpmnJS({ container: $('#InvoiceReceiptP-63530'), height: '95%', width: '95%' }));" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" />
          </div>
        </div>

        Download: [InvoiceReceiptP.bpmn](src/main/resources/InvoiceReceiptP.bpmn)

      operationId: 'Process: InvoiceReceiptP'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/In'
            examples:
              InvoiceReceiptP:
                value:
                  creditor: Great Pizza for Everyone Inc.
                  amount: 300.0
                  invoiceCategory: Travel Expenses
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Out1'
              examples:
                InvoiceReceiptP:
                  value:
                    approved: true
  /decisiondmn/InvoiceReceiptP/invoice-assign-approver:
    head:
      tags:
      - InvoiceReceiptP
      summary: 'DecisionDmn: invoice-assign-approver'
      description: |+
        Decision Table on who must approve the Invoice.


        <div class="diagramCanvas">
          <div class="diagram" id="invoice-assign-approver-64390">
            <img onLoad="openFromUrl('invoice-assign-approver.dmn', new DmnJS({ container: $('#invoice-assign-approver-64390'), height: '95%', width: '95%' }));" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" />
          </div>
        </div>

        Download: [invoice-assign-approver.dmn](src/main/resources/invoice-assign-approver.dmn)

      operationId: 'DecisionDmn: invoice-assign-approver'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/In1'
            examples:
              invoice-assign-approver:
                value:
                  amount: 30.0
                  invoiceCategory: Software License Costs
              budget:
                value:
                  amount: 30.0
                  invoiceCategory: Software License Costs
              day-to-day expense:
                value:
                  amount: 125.0
                  invoiceCategory: Misc
              exceptional:
                value:
                  amount: 12345.0
                  invoiceCategory: Misc
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectEntries_camundala.examples.invoice.InvoiceReceipt.ApproverGroup[]'
              examples:
                invoice-assign-approver:
                  value:
                  - management
  /usertask/InvoiceReceiptP/ApproveInvoiceUT:
    head:
      tags:
      - InvoiceReceiptP
      summary: 'UserTask: ApproveInvoiceUT'
      description: Approve the invoice (or not).
      operationId: 'UserTask: ApproveInvoiceUT'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/In2'
            examples:
              ApproveInvoiceUT:
                value:
                  approved: true
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Out2'
              examples:
                ApproveInvoiceUT:
                  value:
                    approved: true
                Invoice approved:
                  value:
                    approved: true
                Invoice NOT approved:
                  value:
                    approved: false
  /usertask/InvoiceReceiptP/PrepareBankTransferUT:
    head:
      tags:
      - InvoiceReceiptP
      summary: 'UserTask: PrepareBankTransferUT'
      description: Prepare the bank transfer in the Financial Accounting System.
      operationId: 'UserTask: PrepareBankTransferUT'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/In3'
            examples:
              PrepareBankTransferUT:
                value:
                  creditor: Great Pizza for Everyone Inc.
                  amount: 300.0
                  invoiceCategory: Travel Expenses
                  invoiceNumber: I-12345
        required: true
      responses:
        '200':
          description: ''
  /process/ReviewInvoiceP:
    head:
      tags:
      - ReviewInvoiceP
      summary: 'Process: ReviewInvoiceP'
      description: |+
        This starts the Review Invoice Process.


        <div class="diagramCanvas">
          <div class="diagram" id="ReviewInvoiceP-6340">
            <img onLoad="openFromUrl('ReviewInvoiceP.bpmn', new BpmnJS({ container: $('#ReviewInvoiceP-6340'), height: '95%', width: '95%' }));" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" />
          </div>
        </div>

        Download: [ReviewInvoiceP.bpmn](src/main/resources/ReviewInvoiceP.bpmn)

      operationId: 'Process: ReviewInvoiceP'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/In4'
            examples:
              ReviewInvoiceP:
                value:
                  creditor: Great Pizza for Everyone Inc.
                  amount: 300.0
                  invoiceCategory: Travel Expenses
                  invoiceNumber: I-12345
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Out'
              examples:
                ReviewInvoiceP:
                  value:
                    clarified: true
  /usertask/ReviewInvoiceP/AssignReviewerUT:
    head:
      tags:
      - ReviewInvoiceP
      summary: 'UserTask: AssignReviewerUT'
      description: Select the Reviewer.
      operationId: 'UserTask: AssignReviewerUT'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/In3'
            examples:
              AssignReviewerUT:
                value:
                  creditor: Great Pizza for Everyone Inc.
                  amount: 300.0
                  invoiceCategory: Travel Expenses
                  invoiceNumber: I-12345
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Out3'
              examples:
                AssignReviewerUT:
                  value:
                    reviewer: John
  /usertask/ReviewInvoiceP/ReviewInvoiceUT:
    head:
      tags:
      - ReviewInvoiceP
      summary: 'UserTask: ReviewInvoiceUT'
      description: Review Invoice and approve.
      operationId: 'UserTask: ReviewInvoiceUT'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/In3'
            examples:
              ReviewInvoiceUT:
                value:
                  creditor: Great Pizza for Everyone Inc.
                  amount: 300.0
                  invoiceCategory: Travel Expenses
                  invoiceNumber: I-12345
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Out4'
              examples:
                ReviewInvoiceUT:
                  value:
                    clarified: true
                Invoice clarified:
                  value:
                    clarified: true
                Invoice NOT clarified:
                  value:
                    clarified: false
  /usertask/UserTasks/ApproveInvoiceUT:
    head:
      tags:
      - User Tasks
      summary: 'UserTask: ApproveInvoiceUT'
      description: Approve the invoice (or not).
      operationId: 'UserTask: ApproveInvoiceUT'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/In2'
            examples:
              ApproveInvoiceUT:
                value:
                  approved: true
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Out2'
              examples:
                ApproveInvoiceUT:
                  value:
                    approved: true
                Invoice approved:
                  value:
                    approved: true
                Invoice NOT approved:
                  value:
                    approved: false
  /usertask/UserTasks/PrepareBankTransferUT:
    head:
      tags:
      - User Tasks
      summary: 'UserTask: PrepareBankTransferUT'
      description: Prepare the bank transfer in the Financial Accounting System.
      operationId: 'UserTask: PrepareBankTransferUT'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/In3'
            examples:
              PrepareBankTransferUT:
                value:
                  creditor: Great Pizza for Everyone Inc.
                  amount: 300.0
                  invoiceCategory: Travel Expenses
                  invoiceNumber: I-12345
        required: true
      responses:
        '200':
          description: ''
  /usertask/UserTasks/AssignReviewerUT:
    head:
      tags:
      - User Tasks
      summary: 'UserTask: AssignReviewerUT'
      description: Select the Reviewer.
      operationId: 'UserTask: AssignReviewerUT'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/In3'
            examples:
              AssignReviewerUT:
                value:
                  creditor: Great Pizza for Everyone Inc.
                  amount: 300.0
                  invoiceCategory: Travel Expenses
                  invoiceNumber: I-12345
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Out3'
              examples:
                AssignReviewerUT:
                  value:
                    reviewer: John
  /usertask/UserTasks/ReviewInvoiceUT:
    head:
      tags:
      - User Tasks
      summary: 'UserTask: ReviewInvoiceUT'
      description: Review Invoice and approve.
      operationId: 'UserTask: ReviewInvoiceUT'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/In3'
            examples:
              ReviewInvoiceUT:
                value:
                  creditor: Great Pizza for Everyone Inc.
                  amount: 300.0
                  invoiceCategory: Travel Expenses
                  invoiceNumber: I-12345
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Out4'
              examples:
                ReviewInvoiceUT:
                  value:
                    clarified: true
                Invoice clarified:
                  value:
                    clarified: true
                Invoice NOT clarified:
                  value:
                    clarified: false
  /decisiondmn/DMNs/invoice-assign-approver:
    head:
      tags:
      - DMNs
      summary: 'DecisionDmn: invoice-assign-approver'
      description: |+
        Decision Table on who must approve the Invoice.


        <div class="diagramCanvas">
          <div class="diagram" id="invoice-assign-approver-79387">
            <img onLoad="openFromUrl('invoice-assign-approver.dmn', new DmnJS({ container: $('#invoice-assign-approver-79387'), height: '95%', width: '95%' }));" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" />
          </div>
        </div>

        Download: [invoice-assign-approver.dmn](src/main/resources/invoice-assign-approver.dmn)

      operationId: 'DecisionDmn: invoice-assign-approver'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/In1'
            examples:
              invoice-assign-approver:
                value:
                  amount: 30.0
                  invoiceCategory: Software License Costs
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectEntries_camundala.examples.invoice.InvoiceReceipt.ApproverGroup[]'
              examples:
                invoice-assign-approver:
                  value:
                  - management
                budget:
                  value:
                  - management
                day-to-day expense:
                  value:
                  - accounting
                  - sales
components:
  schemas:
    ApproverGroup:
      oneOf:
      - $ref: '#/components/schemas/accounting'
      - $ref: '#/components/schemas/management'
      - $ref: '#/components/schemas/sales'
    CollectEntries_camundala.examples.invoice.InvoiceReceipt.ApproverGroup[]:
      oneOf:
      - $ref: '#/components/schemas/ApproverGroup'
    In:
      required:
      - creditor
      - amount
      - invoiceCategory
      type: object
      properties:
        creditor:
          type: string
        amount:
          type: number
          format: double
        invoiceCategory:
          $ref: '#/components/schemas/InvoiceCategory'
        shouldFail:
          type: boolean
          description: You can let the Archive Service fail for testing.
        invoiceReviewedMock:
          $ref: '#/components/schemas/Out'
    In1:
      required:
      - amount
      - invoiceCategory
      type: object
      properties:
        amount:
          type: number
          format: double
        invoiceCategory:
          $ref: '#/components/schemas/InvoiceCategory'
    In2:
      required:
      - approved
      type: object
      properties:
        approved:
          type: boolean
          description: If true, the Boss accepted the Invoice
      description: Every Invoice has to be accepted by the Boss.
    In3:
      required:
      - creditor
      - amount
      - invoiceCategory
      - invoiceNumber
      type: object
      properties:
        creditor:
          type: string
        amount:
          type: number
          format: double
        invoiceCategory:
          $ref: '#/components/schemas/InvoiceCategory'
        invoiceNumber:
          type: string
        shouldFail:
          type: boolean
          description: You can let the Archive Service fail for testing.
      description: Same Input as _InvoiceReceipt_, only without mocking - no mocking
        in UserTasks
    In4:
      required:
      - creditor
      - amount
      - invoiceCategory
      - invoiceNumber
      type: object
      properties:
        creditor:
          type: string
        amount:
          type: number
          format: double
        invoiceCategory:
          $ref: '#/components/schemas/InvoiceCategory'
        invoiceNumber:
          type: string
        shouldFail:
          type: boolean
          description: You can let the Archive Service fail for testing.
        outputMock:
          $ref: '#/components/schemas/Out'
      description: Same Input as _InvoiceReceipt_, only different Mocking
    InvoiceCategory:
      oneOf:
      - $ref: '#/components/schemas/Misc'
      - $ref: '#/components/schemas/Software License Costs'
      - $ref: '#/components/schemas/Travel Expenses'
    Misc:
      type: object
    Out:
      required:
      - clarified
      type: object
      properties:
        clarified:
          type: boolean
          description: Flag that is set by the Reviewer
      description: Mocking the subProcess _Invoice Receipt_.
    Out1:
      required:
      - approved
      type: object
      properties:
        approved:
          type: boolean
          description: If true, the Boss accepted the Invoice
        clarified:
          type: boolean
          description: Flag that is set by the Reviewer (only set if there was a review).
    Out2:
      required:
      - approved
      type: object
      properties:
        approved:
          type: boolean
          description: If true, the Boss accepted the Invoice
      description: Every Invoice has to be accepted by the Boss.
    Out3:
      required:
      - reviewer
      type: object
      properties:
        reviewer:
          type: string
    Out4:
      required:
      - clarified
      type: object
      properties:
        clarified:
          type: boolean
          description: Flag that is set by the Reviewer
    Software License Costs:
      type: object
    Travel Expenses:
      type: object
    accounting:
      type: object
    management:
      type: object
    sales:
      type: object
